[server]
server_name = localhost
port = 8080
root = ./files

[location]
name = /
root = ./files
index = index.html
method = dElETe
method = POST
method = GET
[location]
name = /cgi
root = ./files/cgi-bin
index = index.php
method = GET
cgi = php:./cgi-bin/php-cgi|py:/usr/local/bin/python3
[location]
name = /upload
root = ./files
upload_path = /Users/mkhairou/Desktop/to_push/webserve_uploads
upload_enable = true
