[server]
server_name = localhost
port = 8080
root = ./webser_site
index = index.html
[location]
name = /
root = ./webser_site
index = index.html
auto_index = true
cgi = php:./cgi-bin/php-cgi
[location]
name = /for
root = ./webser_site/forms
auto_index = true
[location]
name = /cgi
root = ./webser_site/cgi-bin
cgi = py:/usr/local/bin/python3|php:./cgi-bin/php-cgi
[server]
server_name = localhost
port = 8081
root = ./webser_default
index = index.html
